---
title: RISE Physical Therapy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:categories/:title"
    description: ''
    featured-image: ''
    alt-tag: ''
url: https://www.risephysicaltherapy.com
baseurl: 
email: rise@risephysicaltherapy.com
description: Welcome to RISE Physical Therapy. Providing physical therapy in Solana
  Beach, Carlsbad, & Point Loma. Visit us today to schedule your appointment!
logo: img/logos/rise-main-logo.png
people:
- name: Navid Hannavash
  pic: navid
  position: DPT, ATC, CSCS, FAFS | CEO & Owner
  bio: In addition to striving to set up environments to provide the most quality
    care to his patients, Navid enjoys spending time with his friends and family,
    walking his wolf Jasmine around town, and all things sports (especially basketball)
    and food related.
- name: Alex Kelso
  pic: alex
  position: PT, DPT, CAFS, FAFS
  bio: Alex found physical therapy through his own physical struggles, which built
    his passion for working to improve the quality of life of his patients. Alex enjoys
    boating, working on anything with a motor, or cheering on the Florida Gators.
    He holds a doctorate from the University of Southern California, and is an Applied
    Functional Science fellow.
- name: Thomas Russell
  pic: thomas
  position: PT, DPT, CAFS
  bio: From his roots in competitive team sports, Thomas found a passion for sport-specific
    strength and conditioning which lead him to pursue a career in physical therapy.
    He is currently working toward earning his AFS certification, and will be pursuing
    his Certified Strength and Conditioning Specialist certification in the near future
    as well.
- name: Rachel Nesseth
  pic: rachel
  position: PT, DPT, CAFS | Vice President
  bio: Rachel's passion for movement began with dance, which inspired her to pursue
    a career in physical therapy. When not in the clinic with patients, she enjoys
    being outdoors with her dog Emma, creating art, and enjoying good food with family
    and friends.
- name: Kelsey Diaz
  pic: kelsey
  position: PT, DPT
  bio: Kelsey’s first experience with physical therapy came while overcoming injuries
    as a competitive gymnast. She became a group fitness instructor at the University
    of Florida, which helped her realize her passion for helping others stay healthy
    through movement. She earned her doctorate degree in physical therapy from UF
    and relocated to San Diego.
- name: Allison Gentry
  pic: allison
  position: PT, DPT, CAFS
  bio: Ally found physical therapy at an early age while growing up in Tennessee.
    She enjoys improving the lives of others through rehabilitation and helping them
    to reach their personal goals.  Ally enjoys playing with her dog, Arya, running,
    hiking, and spending time with family in her new home of San Diego.
- name: Michael Hollstegge
  pic: michael
  position: PT, DPT, CAFS, TPI-CGFI
  bio: Michael built his foundation for Physical Therapy on his own recovery from
    a high school basketball injury. He's an avid golfer who is as passionate about
    the game as he is about rehabilitating all patients to reach their maximum movement
    potential. Michael is also a certified golf fitness instructor through the Titleist
    Performance Institute who can address your physical limitations, provide you with
    the treatment to correct these limitations, and apply the results to your game.
- name: Justin Ternes
  pic: justin
  position: PT, DPT, CAFS
  bio: Justin found his passion of healing the human body though troubleshooting and
    problem solving his own athletic injuries while growing up in Fayetteville, Arkansas.
    He has developed his treatment to focus on full body movements strongly influenced
    by his co-workers at RISE and Applied Functional Science. In his spare time, he
    is learning how to surf, playing basketball and golf, and exploring his new home
    in Southern California
social:
- title: twitter
  url: http://twitter.com/RISE_PT
- title: facebook
  url: https://www.facebook.com/officialrisephysicaltherapy
- title: google-plus
  url: https://plus.google.com/+RISEPhysicalTherapySolanaBeach/
- title: instagram
  url: https://instagram.com/rise_pt/
- title: linkedin
  url: https://www.linkedin.com/company/rise-physical-therapy
address:
- line: 380 Stevens Ave Suite 314
- line: Solana Beach, CA 92075
markdown: kramdown
permalink: pretty
include:
- _redirects
