url: http://www.zac-heisey.com/ # the base hostname & protocal for the site
baseurl: /rise-v2 # the subpath of dev site on GitHub pages > change to / before pushing live

# Site settings
title: RISE Physical Therapy
email: rise@risephysicaltherapy.com
description: "Welcome to RISE Physical Therapy. Providing physical therapy in Solana Beach, Carlsbad, & Point Loma. Visit us today to schedule your appointment!"
logo: img/logos/rise-main-logo.png

# Team names, titles and social links
people:
- name: Navid Hannavash
  pic: navid
  position: DPT, ATC, CSCS, FAFS | CEO & Owner
  bio: In addition to striving to set up environments to provide the most quality care to his patients, Navid enjoys spending time with his friends and family, walking his wolf Jasmine around town, and all things sports (especially basketball) and food related.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alex Kelso
  pic: alex
  position: Doctor of Physical Therapy
  bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Thomas Russell
  pic: thomas
  position: Doctor of Physical Therapy
  bio: From his roots in competitive team sports, Thomas found a passion for sport-specific strength and conditioning which lead him to pursue a career in physical therapy. He is currently working toward earning his AFS certification, and will be pursing his Certified Strength and Conditioning Specialist certification in the near future as well.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rachel Nesseth
  pic: rachel
  position: Doctor of Physical Therapy
  bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/RISE_PT
  - title: facebook
    url: https://www.facebook.com/officialrisephysicaltherapy
  - title: google-plus
    url: https://plus.google.com/+RISEPhysicalTherapySolanaBeach/
  - title: instagram
    url: https://instagram.com/rise_pt/
  - title: linkedin
    url: https://www.linkedin.com/company/rise-physical-therapy

# Postal address (add as many lines as necessary)
address:
  - line: 380 Stevens Ave Suite 314
  - line: Solana Beach, CA 92075

# Build settings
markdown: kramdown
permalink: pretty
